logging:
  level:
    root: DEBUG
server:
  port: 8074
spring:
  security:
    oauth2:
      client:
        registration:
          joe-test-oidc-auth:
            provider: open-athens-dev
            client-id: hobbitonlibrary.com.oidc-app-v1.50bd6294-0063-4d4a-a1a1-47d691c67e40
            client-secret: gc7uJapV7lrirmRljJUcHEMDv
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
            scope: openid
        provider:
          open-athens-dev:
            issuerUri: https://connect.dev.openathens.net
            authorization-uri: https://connect.dev.openathens.net/oidc/auth
            token-uri: https://connect.dev.openathens.net/oidc/token
            user-info-uri: https://connect.dev.openathens.net/oidc/userinfo


