logging:
  level:
    root: DEBUG
spring:
  security:
    oauth2:
      client:
        registration:
          joe-test-oidc-auth:
            provider: open-athens-dev
            client-id: hobbitonlibrary.com.oidc-app-v1.766a9db9-31c3-48e3-a742-3c6576a06bdd
            client-secret: MRQP6qpoh1i17YQM1N9fcXyyd
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
            scope: openid
        provider:
          open-athens-dev:
            issuerUri: https://connect.dev.openathens.net
            authorization-uri: https://connect.dev.openathens.net/oidc/auth
            token-uri: https://connect.dev.openathens.net/oidc/token
            user-info-uri: https://connect.dev.openathens.net/oidc/userinfo


