logging:
  level:
    root: DEBUG
spring:
  security:
    oauth2:
      client:
        registration:
          joe-test-oidc-auth:
            provider: open-athens-test
            client-id: joetesting.net.oidc-app-v1.e017f170-82b3-46a3-ba21-e6f7dbe467af
            client-secret: F3R5BFzFteWzyWAKJVm6wvb2k
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
            scope: openid
        provider:
          open-athens-test:
            issuerUri: https://connect.test.openathens.net
            authorization-uri: https://connect.test.openathens.net/oidc/auth
            token-uri: https://connect.test.openathens.net/oidc/token
            user-info-uri: https://connect.test.openathens.net/oidc/userinfo


